"""Phase 1 research control-plane schema, owned by this revision."""
from alembic import op
import sqlalchemy as sa

revision = "0001_phase1"
down_revision = None
branch_labels = None
depends_on = None

def _id(): return sa.Column("id", sa.String(), primary_key=True)
def _stamp(name, nullable=False): return sa.Column(name, sa.DateTime(timezone=True), nullable=nullable)

def upgrade():
    op.create_table("research_profiles", _id(), sa.Column("name", sa.String(), nullable=False, unique=True), sa.Column("mode", sa.String(), nullable=False, server_default="GENERIC_DISCOVERY_RESEARCH"))
    op.create_table("mandate_versions", _id(), sa.Column("profile_id",sa.String(),sa.ForeignKey("research_profiles.id",ondelete="RESTRICT"),nullable=False),sa.Column("revision",sa.Integer(),nullable=False),sa.Column("supersedes_version_id",sa.String(),sa.ForeignKey("mandate_versions.id",ondelete="RESTRICT")),sa.Column("mode",sa.String(),nullable=False),sa.Column("horizon_years",sa.Integer(),nullable=False),sa.Column("base_currency",sa.String(),nullable=False),sa.Column("nominal_real",sa.String(),nullable=False),sa.Column("tax_treatment",sa.String(),nullable=False),sa.Column("external_flows",sa.String(),nullable=False),sa.Column("portfolio_scope",sa.String(),nullable=False),sa.Column("universe_version",sa.String(),nullable=False),sa.Column("benchmark_definition",sa.String(),nullable=False),sa.Column("passive_candidate",sa.String()),sa.Column("cash_semantics",sa.String(),nullable=False),sa.Column("risk_free_proxy",sa.String()),sa.Column("reference_capital",sa.Integer(),nullable=False),sa.Column("status",sa.String(),nullable=False),sa.Column("rationale",sa.String(),nullable=False),sa.Column("policy_hash",sa.String(),nullable=False),_stamp("effective_at"),_stamp("review_at",True),_stamp("created_at"),sa.UniqueConstraint("profile_id","revision",name="uq_mandate_profile_revision"),sa.UniqueConstraint("supersedes_version_id",name="uq_mandate_predecessor"),sa.CheckConstraint("revision > 0",name="ck_mandate_revision"),sa.CheckConstraint("status = 'PROVISIONAL'",name="ck_mandate_provisional"),sa.CheckConstraint("mode = 'GENERIC_DISCOVERY_RESEARCH'",name="ck_mandate_mode"))
    op.create_table("risk_budget_versions", _id(),sa.Column("profile_id",sa.String(),sa.ForeignKey("research_profiles.id",ondelete="RESTRICT"),nullable=False),sa.Column("mandate_version_id",sa.String(),sa.ForeignKey("mandate_versions.id",ondelete="RESTRICT"),nullable=False),sa.Column("revision",sa.Integer(),nullable=False),sa.Column("supersedes_version_id",sa.String(),sa.ForeignKey("risk_budget_versions.id",ondelete="RESTRICT")),sa.Column("name",sa.String(),nullable=False),sa.Column("status",sa.String(),nullable=False),sa.Column("rationale",sa.String(),nullable=False),sa.Column("policy_hash",sa.String(),nullable=False),_stamp("created_at"),sa.UniqueConstraint("profile_id","revision",name="uq_risk_profile_revision"),sa.UniqueConstraint("supersedes_version_id",name="uq_risk_predecessor"),sa.CheckConstraint("revision > 0",name="ck_risk_revision"),sa.CheckConstraint("status = 'PROVISIONAL'",name="ck_risk_provisional"))
    op.create_table("research_profile_heads",sa.Column("profile_id",sa.String(),sa.ForeignKey("research_profiles.id",ondelete="RESTRICT"),primary_key=True),sa.Column("mandate_version_id",sa.String(),sa.ForeignKey("mandate_versions.id",ondelete="RESTRICT")),sa.Column("risk_budget_version_id",sa.String(),sa.ForeignKey("risk_budget_versions.id",ondelete="RESTRICT")))
    op.create_table("risk_constraints",_id(),sa.Column("risk_budget_version_id",sa.String(),sa.ForeignKey("risk_budget_versions.id",ondelete="RESTRICT"),nullable=False),sa.Column("constraint_class",sa.String(),nullable=False),sa.Column("metric",sa.String(),nullable=False),sa.Column("unit",sa.String(),nullable=False),sa.Column("horizon",sa.String(),nullable=False),sa.Column("operator",sa.String(),nullable=False),sa.Column("limit_value",sa.Float()),sa.Column("warning_value",sa.Float()),sa.Column("epsilon",sa.Float()),sa.Column("alpha",sa.Float()),sa.Column("uncertainty_version",sa.String()),sa.Column("stress_version",sa.String()),sa.Column("binding_status",sa.String(),nullable=False),sa.Column("calibration_status",sa.String(),nullable=False),sa.Column("missing_reason",sa.String()),sa.UniqueConstraint("risk_budget_version_id","metric",name="uq_risk_constraint_metric"))
    op.create_table("validation_evidence",_id(),sa.Column("claim",sa.String(),nullable=False),sa.Column("status",sa.String(),nullable=False),sa.Column("source_locator",sa.String()),sa.Column("reason",sa.String()),_stamp("created_at"))
    op.create_table("providers",_id(),sa.Column("name",sa.String(),nullable=False,unique=True),sa.Column("version",sa.String()),sa.Column("authority_tier",sa.String(),nullable=False),sa.Column("declarations",sa.JSON(),nullable=False),sa.Column("source_reference",sa.String()),sa.Column("validation_status",sa.String(),nullable=False),_stamp("created_at"),sa.CheckConstraint("validation_status = 'NOT_VERIFIED'",name="ck_provider_unverified"))
    op.create_table("issuers",_id(),sa.Column("legal_name",sa.String(),nullable=False),sa.Column("incorporation_country",sa.String()),sa.Column("lifecycle_status",sa.String(),nullable=False))
    op.create_table("securities",_id(),sa.Column("issuer_id",sa.String(),sa.ForeignKey("issuers.id",ondelete="RESTRICT"),nullable=False),sa.Column("instrument_type",sa.String(),nullable=False),sa.Column("share_class",sa.String()),sa.Column("primary_venue",sa.String(),nullable=False),sa.Column("currency",sa.String(),nullable=False),sa.Column("lifecycle_status",sa.String(),nullable=False))
    op.create_table("evidence_records",_id(),sa.Column("provider_id",sa.String(),sa.ForeignKey("providers.id",ondelete="RESTRICT"),nullable=False),sa.Column("source_locator",sa.String(),nullable=False),sa.Column("subject_type",sa.String(),nullable=False),sa.Column("subject_id",sa.String(),nullable=False),sa.Column("metric",sa.String(),nullable=False),sa.Column("value",sa.JSON()),sa.Column("unit",sa.String()),sa.Column("currency",sa.String()),sa.Column("period",sa.String()),sa.Column("as_of_date",sa.Date()),_stamp("available_at",True),_stamp("retrieved_at",True),_stamp("ingested_at"),_stamp("created_at"),sa.Column("observation_mode",sa.String(),nullable=False),sa.Column("processing_latency_seconds",sa.Integer()),sa.Column("quality_confidence",sa.String()),sa.Column("value_presence",sa.String(),nullable=False),sa.Column("use_status",sa.String(),nullable=False),sa.Column("reason",sa.String()),sa.Column("conflict_group_id",sa.String()),sa.Column("lineage_hash",sa.String()),sa.Column("payload_hash",sa.String()),sa.Column("supersedes_id",sa.String(),sa.ForeignKey("evidence_records.id",ondelete="RESTRICT")),sa.UniqueConstraint("supersedes_id",name="uq_evidence_predecessor"),sa.CheckConstraint("processing_latency_seconds IS NULL OR processing_latency_seconds >= 0",name="ck_evidence_latency"),sa.CheckConstraint("value_presence IN ('PRESENT','MISSING','UNKNOWN','NOT_APPLICABLE')",name="ck_evidence_presence"),sa.CheckConstraint("use_status IN ('NOT_EVALUATED','FRESH','STALE','CONFLICTING','UNAVAILABLE_PIT')",name="ck_evidence_use"),sa.CheckConstraint("observation_mode IN ('LIVE_CAPTURE','HISTORICAL_IMPORT')",name="ck_evidence_mode"),sa.CheckConstraint("value_presence = 'PRESENT' OR use_status IN ('NOT_EVALUATED','UNAVAILABLE_PIT')",name="ck_evidence_presence_use"),sa.CheckConstraint("use_status != 'CONFLICTING' OR (conflict_group_id IS NOT NULL AND length(trim(conflict_group_id)) > 0)",name="ck_evidence_conflict_group"))
    op.create_table("security_identifiers",_id(),sa.Column("security_id",sa.String(),sa.ForeignKey("securities.id",ondelete="RESTRICT"),nullable=False),sa.Column("scheme",sa.String(),nullable=False),sa.Column("value",sa.String(),nullable=False),sa.Column("venue",sa.String()),sa.Column("valid_from",sa.Date(),nullable=False),sa.Column("valid_to",sa.Date()),sa.Column("source_evidence_id",sa.String(),sa.ForeignKey("evidence_records.id",ondelete="RESTRICT")),sa.CheckConstraint("valid_to IS NULL OR valid_to >= valid_from",name="ck_identifier_interval"))
    op.create_table("corporate_actions",_id(),sa.Column("security_id",sa.String(),sa.ForeignKey("securities.id",ondelete="RESTRICT"),nullable=False),sa.Column("action_type",sa.String(),nullable=False),sa.Column("effective_date",sa.Date(),nullable=False),_stamp("tradable_at",True),sa.Column("predecessor_security_id",sa.String(),sa.ForeignKey("securities.id",ondelete="RESTRICT")),sa.Column("successor_security_id",sa.String(),sa.ForeignKey("securities.id",ondelete="RESTRICT")),sa.Column("source_evidence_id",sa.String(),sa.ForeignKey("evidence_records.id",ondelete="RESTRICT")))
    op.create_table("universe_memberships",_id(),sa.Column("universe_version",sa.String(),nullable=False),sa.Column("security_id",sa.String(),sa.ForeignKey("securities.id",ondelete="RESTRICT"),nullable=False),sa.Column("included_from",sa.Date(),nullable=False),sa.Column("included_to",sa.Date()),_stamp("decision_available_at"),sa.Column("reason",sa.String(),nullable=False),sa.Column("source_evidence_id",sa.String(),sa.ForeignKey("evidence_records.id",ondelete="RESTRICT")),sa.CheckConstraint("included_to IS NULL OR included_to >= included_from",name="ck_membership_interval"))
    op.create_table("decision_snapshots",_id(),sa.Column("mandate_version_id",sa.String(),sa.ForeignKey("mandate_versions.id",ondelete="RESTRICT"),nullable=False),sa.Column("risk_budget_version_id",sa.String(),sa.ForeignKey("risk_budget_versions.id",ondelete="RESTRICT"),nullable=False),sa.Column("policy_hash",sa.String(),nullable=False),_stamp("decision_timestamp"),_stamp("tradable_at"),sa.Column("evidence_ids",sa.JSON(),nullable=False),sa.Column("blocker_codes",sa.JSON(),nullable=False),sa.Column("diagnostics",sa.JSON(),nullable=False),_stamp("created_at"))
    for table, cols in [("security_identifiers",("scheme","value","venue")),("evidence_records",("provider_id","subject_type","subject_id","metric")),("universe_memberships",("universe_version","security_id"))]: op.create_index("ix_"+table+"_"+"_".join(cols),table,list(cols))
    for table in ("mandate_versions","risk_budget_versions","risk_constraints","validation_evidence","providers","issuers","securities","evidence_records","security_identifiers","corporate_actions","universe_memberships","decision_snapshots"):
        op.execute(f"CREATE TRIGGER trg_{table}_no_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'immutable {table}'); END")
        op.execute(f"CREATE TRIGGER trg_{table}_no_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'immutable {table}'); END")

def downgrade():
    for table in ("decision_snapshots","universe_memberships","corporate_actions","security_identifiers","evidence_records","securities","issuers","providers","validation_evidence","risk_constraints","research_profile_heads","risk_budget_versions","mandate_versions","research_profiles"):
        op.drop_table(table)
