from __future__ import annotations
import uuid
from datetime import date, datetime, timezone
from sqlalchemy import CheckConstraint, Date, DateTime, ForeignKey, Integer, JSON, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from .db import Base

def uid() -> str: return str(uuid.uuid4())
def utcnow() -> datetime: return datetime.now(timezone.utc)

class ResearchProfile(Base):
    __tablename__="research_profiles"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid)
    name: Mapped[str]=mapped_column(String,unique=True)
    mode: Mapped[str]=mapped_column(String,default="GENERIC_DISCOVERY_RESEARCH")
class ProfileHead(Base):
    __tablename__="research_profile_heads"
    profile_id: Mapped[str]=mapped_column(ForeignKey("research_profiles.id",ondelete="RESTRICT"),primary_key=True)
    mandate_version_id: Mapped[str|None]=mapped_column(ForeignKey("mandate_versions.id",ondelete="RESTRICT"),nullable=True)
    risk_budget_version_id: Mapped[str|None]=mapped_column(ForeignKey("risk_budget_versions.id",ondelete="RESTRICT"),nullable=True)
class MandateVersion(Base):
    __tablename__="mandate_versions"
    __table_args__=(UniqueConstraint("profile_id","revision",name="uq_mandate_profile_revision"),UniqueConstraint("supersedes_version_id",name="uq_mandate_predecessor"),CheckConstraint("revision > 0",name="ck_mandate_revision"),CheckConstraint("status = 'PROVISIONAL'",name="ck_mandate_provisional"),CheckConstraint("mode = 'GENERIC_DISCOVERY_RESEARCH'",name="ck_mandate_mode"))
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); profile_id: Mapped[str]=mapped_column(ForeignKey("research_profiles.id",ondelete="RESTRICT")); revision: Mapped[int]=mapped_column(Integer); supersedes_version_id: Mapped[str|None]=mapped_column(ForeignKey("mandate_versions.id",ondelete="RESTRICT"),nullable=True); mode: Mapped[str]=mapped_column(String,default="GENERIC_DISCOVERY_RESEARCH"); horizon_years: Mapped[int]=mapped_column(Integer); base_currency: Mapped[str]=mapped_column(String); nominal_real: Mapped[str]=mapped_column(String); tax_treatment: Mapped[str]=mapped_column(String); external_flows: Mapped[str]=mapped_column(String); portfolio_scope: Mapped[str]=mapped_column(String); universe_version: Mapped[str]=mapped_column(String); benchmark_definition: Mapped[str]=mapped_column(String); passive_candidate: Mapped[str|None]=mapped_column(String,nullable=True); cash_semantics: Mapped[str]=mapped_column(String); risk_free_proxy: Mapped[str|None]=mapped_column(String,nullable=True); reference_capital: Mapped[int]=mapped_column(Integer); status: Mapped[str]=mapped_column(String,default="PROVISIONAL"); rationale: Mapped[str]=mapped_column(String); policy_hash: Mapped[str]=mapped_column(String); effective_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); review_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class RiskBudgetVersion(Base):
    __tablename__="risk_budget_versions"
    __table_args__=(UniqueConstraint("profile_id","revision",name="uq_risk_profile_revision"),UniqueConstraint("supersedes_version_id",name="uq_risk_predecessor"),CheckConstraint("revision > 0",name="ck_risk_revision"),CheckConstraint("status = 'PROVISIONAL'",name="ck_risk_provisional"))
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); profile_id: Mapped[str]=mapped_column(ForeignKey("research_profiles.id",ondelete="RESTRICT")); mandate_version_id: Mapped[str]=mapped_column(ForeignKey("mandate_versions.id",ondelete="RESTRICT")); revision: Mapped[int]=mapped_column(Integer); supersedes_version_id: Mapped[str|None]=mapped_column(ForeignKey("risk_budget_versions.id",ondelete="RESTRICT"),nullable=True); name: Mapped[str]=mapped_column(String,default="BALANCED_RESEARCH_V1"); status: Mapped[str]=mapped_column(String,default="PROVISIONAL"); rationale: Mapped[str]=mapped_column(String); policy_hash: Mapped[str]=mapped_column(String); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class RiskConstraint(Base):
    __tablename__="risk_constraints"; __table_args__=(UniqueConstraint("risk_budget_version_id","metric",name="uq_risk_constraint_metric"),)
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); risk_budget_version_id: Mapped[str]=mapped_column(ForeignKey("risk_budget_versions.id",ondelete="RESTRICT")); constraint_class: Mapped[str]=mapped_column(String); metric: Mapped[str]=mapped_column(String); unit: Mapped[str]=mapped_column(String); horizon: Mapped[str]=mapped_column(String); operator: Mapped[str]=mapped_column(String); limit_value: Mapped[float|None]=mapped_column(nullable=True); warning_value: Mapped[float|None]=mapped_column(nullable=True); epsilon: Mapped[float|None]=mapped_column(nullable=True); alpha: Mapped[float|None]=mapped_column(nullable=True); uncertainty_version: Mapped[str|None]=mapped_column(String,nullable=True); stress_version: Mapped[str|None]=mapped_column(String,nullable=True); binding_status: Mapped[str]=mapped_column(String,default="DIAGNOSTIC"); calibration_status: Mapped[str]=mapped_column(String,default="NOT_VERIFIED"); missing_reason: Mapped[str|None]=mapped_column(String,nullable=True)
class ResearchRiskEditorMarker(Base):
    __tablename__="research_risk_editor_markers"
    __table_args__=(CheckConstraint("schema_version = 'RESEARCH_RISK_EDITOR_V1'",name="ck_editor_marker_schema"),CheckConstraint("length(document_sha256)=64 AND document_sha256=lower(document_sha256)",name="ck_editor_marker_digest"),CheckConstraint("length(created_at) > 0",name="ck_editor_marker_created_at"))
    risk_budget_version_id: Mapped[str]=mapped_column(ForeignKey("risk_budget_versions.id",ondelete="RESTRICT"),primary_key=True)
    schema_version: Mapped[str]=mapped_column(String,default="RESEARCH_RISK_EDITOR_V1")
    document_sha256: Mapped[str]=mapped_column(String)
    created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class ResearchRiskEditorDocument(Base):
    __tablename__="research_risk_editor_documents"
    __table_args__=(CheckConstraint("schema_version = 'RESEARCH_RISK_EDITOR_V1'",name="ck_editor_document_schema"),CheckConstraint("json_valid(canonical_document)=1",name="ck_editor_document_json"),CheckConstraint("length(created_at) > 0",name="ck_editor_document_created_at"))
    risk_budget_version_id: Mapped[str]=mapped_column(ForeignKey("research_risk_editor_markers.risk_budget_version_id",ondelete="RESTRICT"),primary_key=True)
    schema_version: Mapped[str]=mapped_column(String,default="RESEARCH_RISK_EDITOR_V1")
    canonical_document: Mapped[str]=mapped_column(String)
    created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class ValidationEvidence(Base):
    __tablename__="validation_evidence"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); claim: Mapped[str]=mapped_column(String); status: Mapped[str]=mapped_column(String,default="NOT_VERIFIED"); source_locator: Mapped[str|None]=mapped_column(String,nullable=True); reason: Mapped[str|None]=mapped_column(String,nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class Provider(Base):
    __tablename__="providers"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); name: Mapped[str]=mapped_column(String,unique=True); version: Mapped[str|None]=mapped_column(String,nullable=True); authority_tier: Mapped[str]=mapped_column(String); declarations: Mapped[dict]=mapped_column(JSON,default=dict); source_reference: Mapped[str|None]=mapped_column(String,nullable=True); validation_status: Mapped[str]=mapped_column(String,default="NOT_VERIFIED"); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class Issuer(Base):
    __tablename__="issuers"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); legal_name: Mapped[str]=mapped_column(String); incorporation_country: Mapped[str|None]=mapped_column(String,nullable=True); lifecycle_status: Mapped[str]=mapped_column(String,default="ACTIVE")
class Security(Base):
    __tablename__="securities"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); issuer_id: Mapped[str]=mapped_column(ForeignKey("issuers.id",ondelete="RESTRICT")); instrument_type: Mapped[str]=mapped_column(String); share_class: Mapped[str|None]=mapped_column(String,nullable=True); primary_venue: Mapped[str]=mapped_column(String); currency: Mapped[str]=mapped_column(String); lifecycle_status: Mapped[str]=mapped_column(String,default="ACTIVE")
class SecurityIdentifier(Base):
    __tablename__="security_identifiers"; __table_args__=(CheckConstraint("valid_to IS NULL OR valid_to >= valid_from",name="ck_identifier_interval"),)
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); security_id: Mapped[str]=mapped_column(ForeignKey("securities.id",ondelete="RESTRICT")); scheme: Mapped[str]=mapped_column(String); value: Mapped[str]=mapped_column(String); venue: Mapped[str|None]=mapped_column(String,nullable=True); valid_from: Mapped[date]=mapped_column(Date); valid_to: Mapped[date|None]=mapped_column(Date,nullable=True); source_evidence_id: Mapped[str|None]=mapped_column(ForeignKey("evidence_records.id",ondelete="RESTRICT"),nullable=True)
class CorporateAction(Base):
    __tablename__="corporate_actions"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); security_id: Mapped[str]=mapped_column(ForeignKey("securities.id",ondelete="RESTRICT")); action_type: Mapped[str]=mapped_column(String); effective_date: Mapped[date]=mapped_column(Date); tradable_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); predecessor_security_id: Mapped[str|None]=mapped_column(ForeignKey("securities.id",ondelete="RESTRICT"),nullable=True); successor_security_id: Mapped[str|None]=mapped_column(ForeignKey("securities.id",ondelete="RESTRICT"),nullable=True); source_evidence_id: Mapped[str|None]=mapped_column(ForeignKey("evidence_records.id",ondelete="RESTRICT"),nullable=True)
class UniverseMembership(Base):
    __tablename__="universe_memberships"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); universe_version: Mapped[str]=mapped_column(String); security_id: Mapped[str]=mapped_column(ForeignKey("securities.id",ondelete="RESTRICT")); included_from: Mapped[date]=mapped_column(Date); included_to: Mapped[date|None]=mapped_column(Date,nullable=True); decision_available_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); reason: Mapped[str]=mapped_column(String); source_evidence_id: Mapped[str|None]=mapped_column(ForeignKey("evidence_records.id",ondelete="RESTRICT"),nullable=True)
class EvidenceRecord(Base):
    __tablename__="evidence_records"; __table_args__=(UniqueConstraint("supersedes_id",name="uq_evidence_predecessor"),CheckConstraint("value_presence = 'PRESENT' OR use_status IN ('NOT_EVALUATED','UNAVAILABLE_PIT')",name="ck_evidence_presence_use"),CheckConstraint("use_status != 'CONFLICTING' OR (conflict_group_id IS NOT NULL AND length(trim(conflict_group_id)) > 0)",name="ck_evidence_conflict_group"))
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); provider_id: Mapped[str]=mapped_column(ForeignKey("providers.id",ondelete="RESTRICT")); source_locator: Mapped[str]=mapped_column(String); subject_type: Mapped[str]=mapped_column(String); subject_id: Mapped[str]=mapped_column(String); metric: Mapped[str]=mapped_column(String); value: Mapped[object|None]=mapped_column(JSON,nullable=True); unit: Mapped[str|None]=mapped_column(String,nullable=True); currency: Mapped[str|None]=mapped_column(String,nullable=True); period: Mapped[str|None]=mapped_column(String,nullable=True); as_of_date: Mapped[date|None]=mapped_column(Date,nullable=True); available_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); retrieved_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); ingested_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); observation_mode: Mapped[str]=mapped_column(String); processing_latency_seconds: Mapped[int|None]=mapped_column(Integer,nullable=True); quality_confidence: Mapped[str|None]=mapped_column(String,nullable=True); value_presence: Mapped[str]=mapped_column(String); use_status: Mapped[str]=mapped_column(String); reason: Mapped[str|None]=mapped_column(String,nullable=True); conflict_group_id: Mapped[str|None]=mapped_column(String,nullable=True); lineage_hash: Mapped[str|None]=mapped_column(String,nullable=True); payload_hash: Mapped[str|None]=mapped_column(String,nullable=True); supersedes_id: Mapped[str|None]=mapped_column(ForeignKey("evidence_records.id",ondelete="RESTRICT"),nullable=True)
class DecisionSnapshot(Base):
    __tablename__="decision_snapshots"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); mandate_version_id: Mapped[str]=mapped_column(ForeignKey("mandate_versions.id",ondelete="RESTRICT")); risk_budget_version_id: Mapped[str]=mapped_column(ForeignKey("risk_budget_versions.id",ondelete="RESTRICT")); policy_hash: Mapped[str]=mapped_column(String); decision_timestamp: Mapped[datetime]=mapped_column(DateTime(timezone=True)); tradable_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); evidence_ids: Mapped[list]=mapped_column(JSON); blocker_codes: Mapped[list]=mapped_column(JSON); diagnostics: Mapped[list]=mapped_column(JSON); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)

# Phase 2 staging is deliberately isolated from authoritative issuer/security/universe tables.
class LicenseEvidenceVersion(Base):
    __tablename__="license_evidence_versions"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); provider_id: Mapped[str]=mapped_column(ForeignKey("providers.id",ondelete="RESTRICT")); artifact_sha256: Mapped[str]=mapped_column(String); canonical_url: Mapped[str]=mapped_column(String); retrieved_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); reviewer: Mapped[str]=mapped_column(String); reason: Mapped[str]=mapped_column(String); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class LicenseUsePermission(Base):
    __tablename__="license_use_permissions"; __table_args__=(UniqueConstraint("license_evidence_version_id","use_type",name="uq_license_use"),)
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); license_evidence_version_id: Mapped[str]=mapped_column(ForeignKey("license_evidence_versions.id",ondelete="RESTRICT")); use_type: Mapped[str]=mapped_column(String); permission: Mapped[str]=mapped_column(String); duty: Mapped[str|None]=mapped_column(String,nullable=True)
class ProviderDatasetVersion(Base):
    __tablename__="provider_dataset_versions"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); provider_id: Mapped[str]=mapped_column(ForeignKey("providers.id",ondelete="RESTRICT")); dataset_name: Mapped[str]=mapped_column(String); semantic_version: Mapped[str]=mapped_column(String); endpoint_url: Mapped[str]=mapped_column(String); parser_name: Mapped[str]=mapped_column(String); parser_hash: Mapped[str]=mapped_column(String); license_evidence_version_id: Mapped[str]=mapped_column(ForeignKey("license_evidence_versions.id",ondelete="RESTRICT"),nullable=False); timestamp_semantics: Mapped[str]=mapped_column(String); rate_policy: Mapped[dict]=mapped_column(JSON); validation_status: Mapped[str]=mapped_column(String,default="NOT_VERIFIED"); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class CaptureScope(Base):
    __tablename__="capture_scopes"; __table_args__=(UniqueConstraint("provider_dataset_version_id","capture_scope_key",name="uq_capture_scope"),)
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); provider_dataset_version_id: Mapped[str]=mapped_column(ForeignKey("provider_dataset_versions.id",ondelete="RESTRICT")); capture_scope_key: Mapped[str]=mapped_column(String); request_identity: Mapped[str]=mapped_column(String); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class IngestionRun(Base):
    __tablename__="ingestion_runs"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); capture_scope_id: Mapped[str]=mapped_column(ForeignKey("capture_scopes.id",ondelete="RESTRICT")); request_fingerprint: Mapped[str]=mapped_column(String); state: Mapped[str]=mapped_column(String); request_started_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); response_completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); error_code: Mapped[str|None]=mapped_column(String,nullable=True); error_reason: Mapped[str|None]=mapped_column(String,nullable=True); retry_of_id: Mapped[str|None]=mapped_column(ForeignKey("ingestion_runs.id",ondelete="RESTRICT"),nullable=True); configuration_hash: Mapped[str]=mapped_column(String); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class IngestionAttempt(Base):
    __tablename__="ingestion_attempts"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); run_id: Mapped[str]=mapped_column(ForeignKey("ingestion_runs.id",ondelete="RESTRICT")); part_name: Mapped[str]=mapped_column(String); request_started_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); response_completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); http_status: Mapped[int|None]=mapped_column(Integer,nullable=True); response_headers: Mapped[dict|None]=mapped_column(JSON,nullable=True); final_url: Mapped[str|None]=mapped_column(String,nullable=True); redirect_count: Mapped[int]=mapped_column(Integer,default=0); redirect_chain: Mapped[list|None]=mapped_column(JSON,nullable=True); error_code: Mapped[str|None]=mapped_column(String,nullable=True); raw_sha256: Mapped[str|None]=mapped_column(ForeignKey("raw_objects.sha256",ondelete="RESTRICT"),nullable=True)
class RawObject(Base):
    __tablename__="raw_objects"; __table_args__=(CheckConstraint("length(sha256)=64 AND sha256=lower(sha256)",name="ck_raw_sha"),)
    sha256: Mapped[str]=mapped_column(String,primary_key=True); byte_length: Mapped[int]=mapped_column(Integer); object_key: Mapped[str]=mapped_column(String,unique=True); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class SourceSnapshot(Base):
    __tablename__="source_snapshots"; __table_args__=(UniqueConstraint("capture_scope_id","manifest_sha256",name="uq_snapshot_manifest"),)
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); capture_scope_id: Mapped[str]=mapped_column(ForeignKey("capture_scopes.id",ondelete="RESTRICT")); run_id: Mapped[str]=mapped_column(ForeignKey("ingestion_runs.id",ondelete="RESTRICT")); manifest: Mapped[list]=mapped_column(JSON); manifest_sha256: Mapped[str]=mapped_column(String); parser_version: Mapped[str]=mapped_column(String); parser_hash: Mapped[str]=mapped_column(String); observed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); usable_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); state: Mapped[str]=mapped_column(String); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class SourceSnapshotPart(Base):
    __tablename__="source_snapshot_parts"; __table_args__=(UniqueConstraint("snapshot_id","ordinal",name="uq_part_ordinal"),UniqueConstraint("snapshot_id","part_name",name="uq_part_name"))
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); snapshot_id: Mapped[str]=mapped_column(ForeignKey("source_snapshots.id",ondelete="RESTRICT")); ordinal: Mapped[int]=mapped_column(Integer); part_name: Mapped[str]=mapped_column(String); raw_sha256: Mapped[str]=mapped_column(ForeignKey("raw_objects.sha256",ondelete="RESTRICT")); byte_length: Mapped[int]=mapped_column(Integer); media_type: Mapped[str]=mapped_column(String); response_completed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); http_status: Mapped[int|None]=mapped_column(Integer,nullable=True); response_headers: Mapped[dict|None]=mapped_column(JSON,nullable=True); final_url: Mapped[str|None]=mapped_column(String,nullable=True); redirect_count: Mapped[int|None]=mapped_column(Integer,nullable=True); redirect_chain: Mapped[list|None]=mapped_column(JSON,nullable=True); request_started_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); source_time_text: Mapped[str|None]=mapped_column(String,nullable=True); source_timezone: Mapped[str|None]=mapped_column(String,nullable=True); source_precision: Mapped[str|None]=mapped_column(String,nullable=True); source_published_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); available_at_claimed: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); available_at_validated: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); source_time_reason: Mapped[str|None]=mapped_column(String,nullable=True)
class SourceRow(Base):
    __tablename__="source_rows"; __table_args__=(UniqueConstraint("snapshot_id","row_key",name="uq_source_row"),)
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); snapshot_id: Mapped[str]=mapped_column(ForeignKey("source_snapshots.id",ondelete="RESTRICT")); part_id: Mapped[str]=mapped_column(ForeignKey("source_snapshot_parts.id",ondelete="RESTRICT")); row_key: Mapped[str]=mapped_column(String); row_hash: Mapped[str]=mapped_column(String); normalized: Mapped[dict]=mapped_column(JSON)
class DatasetHead(Base):
    __tablename__="dataset_heads"; capture_scope_id: Mapped[str]=mapped_column(ForeignKey("capture_scopes.id",ondelete="RESTRICT"),primary_key=True); snapshot_id: Mapped[str]=mapped_column(ForeignKey("source_snapshots.id",ondelete="RESTRICT")); updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class RunSnapshotResult(Base):
    __tablename__="run_snapshot_results"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); run_id: Mapped[str]=mapped_column(ForeignKey("ingestion_runs.id",ondelete="RESTRICT"),unique=True); snapshot_id: Mapped[str]=mapped_column(ForeignKey("source_snapshots.id",ondelete="RESTRICT")); result_type: Mapped[str]=mapped_column(String); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class SourceSecurityCandidate(Base):
    __tablename__="source_security_candidates"; __table_args__=(UniqueConstraint("capture_scope_id","stable_key",name="uq_candidate_key"),)
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); capture_scope_id: Mapped[str]=mapped_column(ForeignKey("capture_scopes.id",ondelete="RESTRICT")); stable_key: Mapped[str]=mapped_column(String); state: Mapped[str]=mapped_column(String,default="UNRESOLVED"); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class StagedMembershipEvent(Base):
    __tablename__="staged_membership_events"
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); candidate_id: Mapped[str]=mapped_column(ForeignKey("source_security_candidates.id",ondelete="RESTRICT")); snapshot_id: Mapped[str]=mapped_column(ForeignKey("source_snapshots.id",ondelete="RESTRICT")); event_type: Mapped[str]=mapped_column(String); observed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); usable_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); reason: Mapped[str]=mapped_column(String)
class IdentityReviewRevision(Base):
    __tablename__="identity_review_revisions"; __table_args__=(UniqueConstraint("supersedes_id",name="uq_identity_predecessor"),)
    id: Mapped[str]=mapped_column(String,primary_key=True,default=uid); candidate_id: Mapped[str]=mapped_column(ForeignKey("source_security_candidates.id",ondelete="RESTRICT")); supersedes_id: Mapped[str|None]=mapped_column(ForeignKey("identity_review_revisions.id",ondelete="RESTRICT"),nullable=True); revision: Mapped[int]=mapped_column(Integer); status: Mapped[str]=mapped_column(String); actor: Mapped[str]=mapped_column(String); method_version: Mapped[str]=mapped_column(String); evidence_ids: Mapped[list]=mapped_column(JSON); reason: Mapped[str]=mapped_column(String); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class IdentityReviewHead(Base):
    __tablename__="identity_review_heads"; candidate_id: Mapped[str]=mapped_column(ForeignKey("source_security_candidates.id",ondelete="RESTRICT"),primary_key=True); revision_id: Mapped[str]=mapped_column(ForeignKey("identity_review_revisions.id",ondelete="RESTRICT"))
